version: '2'

services:
  myapp:
    tty: true
    image: docker.io/bitnami/laravel:8
    container_name: products_ms
    environment:
      - DATABASE_URL='mysql://products_user:secret@104.197.88.238:3306/products_db'
      - DB_HOST=104.197.88.238
      - DB_PORT=3306
      - DB_USERNAME=products_user
      - DB_DATABASE=products_db
      - DB_PASSWORD=secret
    ports:
      - 8000:3000
    volumes:
      - ./:/app